name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push backend to hub
        env:
          HF_TOKEN: ${{ secrets.DeepStegAI }}
        run: |
          cd backend
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-deploy backend to Hugging Face"
          git push --force https://hjsudarshan:$HF_TOKEN@huggingface.co/spaces/hjsudarshan/deepstegai-backend HEAD:main
